config/routes.rb
Wandrr::Application.routes.draw do
  devise_for :users
  resources :trips do
    resources :destinations
    resources :comments, :only => [:create, :destroy]
    resources :likes, :only => [:create, :update, :destroy, :index]
  end
  resources :dashboard
  scope "/user" do
      resources :trips
  end
  resources :user, :only => ["show"]

  root to: "home#index"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_user, :only => [:show, :edit, :update]

  def index
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to dashboard_path(@user), notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :location, :email)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_form.html.erb
<%= form_for @user, url: dashboard_path(@user), html: { method: :put } do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_area :surname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboard/edit.html.erb
<% if current_user[:id] == @user.id %>
	<h1>Editing User</h1>

	<%= render 'form' %>

	<%= link_to 'Back', dashboard_path(@user) %>
<% else %>
	<h1>Access Denied! <%= link_to "Back", :back %> </h1>
<% end %>

app/views/dashboard/show.html.erb
<% if current_user[:id] == @user.id %>
	<p id="notice"><%= notice %></p>


		<h2>Hello <%= @user.full_name %> </h2>
	   	<table class="table">
			<tr>
				<th>Name</th>
				<th>Surname</th>
				<th>Email</th>
				<th>Location</th>
				<th>Registered</th>
				<th>Options</th>
			</tr>
			<tbody>
				<tr>
					<td><%= @user.name.nil? ? "" : @user.name %></td>
					<td><%= @user.surname.nil? ? "" : @user.surname %></td>
					<td><%= @user.email.nil? ? "" : @user.email %></td>
					<td><%= @user.location.nil? ? "" : @user.location %></td>
					<td><%= @user.created_at.nil? ? "" : @user.created_at %></td>
					<td><%= link_to "Edit", edit_dashboard_path(@user.id) %></td>
				</tr>
			</tbody>
		</table>
		<% yes = "yes" %>
		<p><%= link_to "Reset Password", edit_user_registration_path(:reset => yes) %></p>
		<p><%= link_to "Cancel Account", edit_user_registration_path(:cancel => yes) %></p>

		<h2>My trips</h2>

		<table class="table">
		  <thead>
		    <tr>
		      <th>Name</th>
		      <th>Description</th>
		      <th>Destination Count</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @user.trips.each do |trip| %>
		      <tr>
		        <td><%= trip.name %></td>
		        <td><%= trip.description %></td>
				<td><%= link_to trip.count_dest, trip_destinations_path(trip.id) %></td>
		        <td><%= link_to 'Show', trip %></td>
			    <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
			    <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		      </tr>
		    <% end %>
		  </tbody>
		</table>
<% else %>
	<h1>Access Denied! <%= link_to "Back", :back %> </h1>
<% end %>