config/routes.rb
Wandrr::Application.routes.draw do
  devise_for :users
  resources :trips do
    resources :destinations
    resources :comments, :only => [:create, :destroy]
    resources :likes, :only => [:create, :update, :destroy, :index]
  end
  resources :dashboard
  scope "/user" do
      resources :trips
  end
  resources :user, :only => ["show"]

  root to: "home#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :destinations, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :likes, :dependent => :destroy

  validates :name, :description, presence: true
  validates :description, length: {maximum: 200}

  scope :search, ->(search) {where('name LIKE ? OR description like ?', "%#{search}%", "%#{search}%")}

  def self.sort_column(sort)
    column_names.include?(sort) ? sort : "name"
  end

  def self.sort_direction(direction = "desc")
    %w[asc desc].include?(direction) ? direction : "asc"
  end

  def likes_count
    likes.likes.count
  end

  def dislikes_count
    likes.dislikes.count
  end

  def increse_views
    self.shown  += 1
    self.save
  end

  def count_dest
    self.destinations.count
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy, :show]
  before_action :set_user, only: [:show, :edit, :new, :index, :create, :show]
  helper_method :sort_column, :sort_direction

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.search(params[:search]).order(Trip.sort_column(params[:sort]) + " " + Trip.sort_direction(params[:direction])).paginate(:page => params[:page], :per_page =>5)
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @comment = Comment.new
    @trip.increse_views
    @like = Like.find_by_user_id_and_trip_id(current_user[:id], @trip.id)
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = @user.trips.new(trip_params)

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render action: 'show', status: :created, location: @trip }
      else
        format.html { render action: 'new' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end
    def set_user
      @user = User.find(current_user[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :description)
    end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_comment.html.erb
<%= form_for @comment, url: trip_comments_path(@trip) do |f| %>
  <%= f.hidden_field :author_id, value: current_user[:id] %>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_comment.posts.html.erb
<h3>Posts</h3>
<ol class="commentlist">
	<% @trip.comments.each do |comment| %>
	<li>
		<div class="commenttext">
			<cite><%= link_to comment.author.full_name, user_path(comment.author_id) %></cite><br>
			<%= comment.post %><br><br>
			<span class="date"><%= comment.created_at %></span>
		</div>
		<% if @trip.user_id == @user.id %>
			<%= link_to 'Delete', trip_comment_path(@trip, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</li>
	<% end %>
</ol>

app/views/trips/_destinations.html.erb
<table class="table">
	<tr>
		<th>Destination</th>
		<th>Description</th>
		<th>Show</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	<% @trip.destinations.each do |destination|%>
	<tr>
		<td><%= destination.name %></td>
		<td><%= destination.description %></td>
		<td><%= link_to "Show", trip_destination_path(@trip, destination) %></td>
		<% if @trip.user_id == @user.id %>
			<td><%= link_to "Edit", edit_trip_destination_path(@trip, destination) %></td>
			<td><%= link_to "Delete", trip_destination_path(@trip, destination), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% else %>
			<td> - </td>
			<td> - </td>
		<% end %>
	</tr>
	<% end %>
	<tr>
		<tr>
			<% if @trip.user_id == @user.id %>
				<%= link_to "New Destination", new_trip_destination_path(@trip) %>
			<% end %>
		</tr>
	</tr>
</table>

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trips/_likes.both.html.erb
<%= link_to "Likes:", trip_likes_path(@trip.id) %>
<span style="color:green;">
	+<%= @trip.likes_count %>
</span>
<span style="color:red;">
	-<%= @trip.dislikes_count %>
</span>
<br>
<span>
	<%= link_to "Like", trip_likes_path(@trip, likes: {like: true, user_id: current_user[:id]}), method: :post%>
</span>
/
<span>
	<%= link_to "Dislike", trip_likes_path(@trip, likes: {like: false, user_id: current_user[:id]}), method: :post %>
</span>

app/views/trips/_likes.dislike.html.erb
<%= link_to "Likes:", trip_likes_path(@trip.id) %>
<span style="color:green;">
	+<%= @trip.likes_count%>
</span>
<span style="color:red;">
	-<%= @trip.dislikes_count %>
</span>
<br>
<span>
	<%= link_to "Dislike", trip_like_path(@trip.id, @like.id, likes: {like: false, user_id: current_user[:id]}), method: :put %>
</span>

app/views/trips/_likes.html.erb
<div>
	<% if @like.nil? %>
		<%= render "likes.both" %>
	<% else %>
  	<% if(@like.like == true) %>
  		<%= render "likes.dislike" %>
  	<% else %>
  		<%= render "likes.like" %>
  	<% end %>
  <% end %>
</div>

app/views/trips/_likes.like.html.erb
<%= link_to "Likes:", trip_likes_path(@trip.id) %>
<span style="color:green;">
	+<%= @trip.likes_count %>
</span>
<span style="color:red;">
	-<%= @trip.dislikes_count %>
</span>
<br>
<span>
	<%= link_to "Like", trip_like_path(@trip.id, @like.id, likes: {like: true, user_id: current_user[:id]}), method: :put %>
<span>

app/views/trips/_trips.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= hidden_field_tag :trip, params[:trip] %>

<h1>Listing trips</h1>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "description" %></th>
      <th>Destination Count</th>
      <th>User</th>
      <th><%= sortable "shown" %></th>
	  <th>Likes</th>
    </tr>
  </thead>

  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.name %></td>
        <td><%= trip.description %></td>
		<td><%= link_to trip.count_dest, trip_destinations_path(trip.id) %></td>
		<td><%= link_to trip.user.full_name, user_path(trip.user_id) %></td>
		<td><%= trip.shown %></td>
		<td>
			<span style="color:green;">
				+<%= trip.likes_count %>
			</span>
			<span style="color:red;">
				-<%= trip.dislikes_count %>
			</span>
		</td>
        <td><%= link_to 'Show', trip %></td>
		<% if trip.user_id == @user.id %>
	        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
	        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% else %>
			<td> - </td>
			<td> - </td>
		<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @trips %>
<br>

app/views/trips/edit.html.erb
<% if @trip.user_id == @user.id %>
	<h1>Editing trip</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @trip %> |
	<%= link_to 'Back', :back %>
<% else %>
	<h1>Access Denied! <%= link_to "Back", :back %> </h1>
<% end %>

app/views/trips/index.html.erb
<%= form_tag (@trip), :method => 'get', :id => "trips_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="trips"><%= render 'trips' %></div>
<% end %>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/trips/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trip.description %>
</p>
<p>
  <%= render "likes" %>
</p>

<%= render "destinations" %>

<br><span>----------------------------------------</span><br>

<% if @trip.user_id == @user.id %>
	<%= link_to 'Edit', edit_trip_path(@trip) %> |
<% end %>
<%= link_to 'Back', :back%>

<br><span>----------------------------------------</span><br>

<%= render "comment" %>

<br><span>----------------------------------------</span><br>
<%= render "comment.posts" %>

app/views/trips/trips.js.erb
$("#trips").html("<%= escape_javascript(render("trips")) %>");